package pdfgen

import (
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
	"github.com/tafolabi009/backend/go_backend/internal/models"
)

// GenerateValidationReport generates a PDF validation report
func GenerateValidationReport(validation *models.Validation, results *models.ValidationResults) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()

	// Header
	pdf.SetFont("Arial", "B", 24)
	pdf.SetTextColor(31, 78, 121)
	pdf.Cell(0, 15, "Synthos AI Validation Report")
	pdf.Ln(20)

	// Validation ID and Date
	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(0, 0, 0)
	pdf.Cell(50, 8, "Validation ID:")
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(0, 8, validation.ID)
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 12)
	pdf.Cell(50, 8, "Dataset ID:")
	pdf.SetFont("Arial", "B", 12)
	pdf.Cell(0, 8, validation.DatasetID)
	pdf.Ln(8)

	pdf.SetFont("Arial", "", 12)
	pdf.Cell(50, 8, "Completed:")
	pdf.SetFont("Arial", "B", 12)
	if validation.CompletedAt != nil {
		pdf.Cell(0, 8, validation.CompletedAt.Format("January 2, 2006 15:04 MST"))
	}
	pdf.Ln(15)

	// Risk Assessment Section
	pdf.SetFont("Arial", "B", 16)
	pdf.SetTextColor(31, 78, 121)
	pdf.Cell(0, 10, "Risk Assessment")
	pdf.Ln(12)

	// Risk Score with color coding
	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(0, 0, 0)
	pdf.Cell(50, 8, "Risk Score:")
	
	if validation.RiskScore != nil {
		riskScore := *validation.RiskScore
		if riskScore < 30 {
			pdf.SetTextColor(0, 128, 0) // Green
		} else if riskScore < 60 {
			pdf.SetTextColor(255, 165, 0) // Orange
		} else {
			pdf.SetTextColor(255, 0, 0) // Red
		}
		pdf.SetFont("Arial", "B", 16)
		pdf.Cell(0, 8, fmt.Sprintf("%d / 100", riskScore))
	}
	pdf.Ln(10)

	// Risk Level
	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(0, 0, 0)
	pdf.Cell(50, 8, "Risk Level:")
	pdf.SetFont("Arial", "B", 12)
	if validation.RiskLevel != nil {
		pdf.Cell(0, 8, *validation.RiskLevel)
	}
	pdf.Ln(10)

	// Recommendation
	pdf.SetFont("Arial", "", 12)
	pdf.Cell(50, 8, "Recommendation:")
	pdf.SetFont("Arial", "B", 12)
	if validation.Recommendation != nil {
		pdf.Cell(0, 8, *validation.Recommendation)
	}
	pdf.Ln(10)

	// Warranty Eligible
	pdf.SetFont("Arial", "", 12)
	pdf.Cell(50, 8, "Warranty Eligible:")
	pdf.SetFont("Arial", "B", 12)
	if validation.WarrantyEligible != nil && *validation.WarrantyEligible {
		pdf.SetTextColor(0, 128, 0)
		pdf.Cell(0, 8, "Yes")
	} else {
		pdf.SetTextColor(255, 0, 0)
		pdf.Cell(0, 8, "No")
	}
	pdf.Ln(15)

	// Performance Predictions Section
	if results != nil {
		pdf.SetFont("Arial", "B", 16)
		pdf.SetTextColor(31, 78, 121)
		pdf.Cell(0, 10, "Performance Predictions")
		pdf.Ln(12)

		pdf.SetFont("Arial", "", 12)
		pdf.SetTextColor(0, 0, 0)
		pdf.Cell(60, 8, "Predicted Accuracy:")
		pdf.SetFont("Arial", "B", 12)
		pdf.Cell(0, 8, fmt.Sprintf("%.2f%%", results.PredictedPerformance.Accuracy*100))
		pdf.Ln(8)

		pdf.SetFont("Arial", "", 12)
		pdf.Cell(60, 8, "Confidence Interval:")
		pdf.SetFont("Arial", "B", 12)
		pdf.Cell(0, 8, fmt.Sprintf("%.2f%% - %.2f%%", 
			results.PredictedPerformance.ConfidenceInterval[0]*100,
			results.PredictedPerformance.ConfidenceInterval[1]*100))
		pdf.Ln(8)

		pdf.SetFont("Arial", "", 12)
		pdf.Cell(60, 8, "Collapse Probability:")
		pdf.SetFont("Arial", "B", 12)
		if results.CollapseProbability < 0.1 {
			pdf.SetTextColor(0, 128, 0)
		} else if results.CollapseProbability < 0.3 {
			pdf.SetTextColor(255, 165, 0)
		} else {
			pdf.SetTextColor(255, 0, 0)
		}
		pdf.Cell(0, 8, fmt.Sprintf("%.2f%%", results.CollapseProbability*100))
		pdf.Ln(15)

		// Dimension Scores
		if len(results.Dimensions) > 0 {
			pdf.SetFont("Arial", "B", 16)
			pdf.SetTextColor(31, 78, 121)
			pdf.Cell(0, 10, "Dimension Analysis")
			pdf.Ln(12)

			for dim, score := range results.Dimensions {
				pdf.SetFont("Arial", "", 11)
				pdf.SetTextColor(0, 0, 0)
				pdf.Cell(90, 7, dim+":")
				pdf.SetFont("Arial", "B", 11)
				
				if score >= 70 {
					pdf.SetTextColor(0, 128, 0)
				} else if score >= 50 {
					pdf.SetTextColor(255, 165, 0)
				} else {
					pdf.SetTextColor(255, 0, 0)
				}
				pdf.Cell(0, 7, fmt.Sprintf("%d / 100", score))
				pdf.Ln(7)
			}
		}
	}

	// Footer
	pdf.Ln(15)
	pdf.SetFont("Arial", "I", 10)
	pdf.SetTextColor(128, 128, 128)
	pdf.Cell(0, 8, "Generated by Synthos AI - "+time.Now().Format("January 2, 2006"))
	pdf.Ln(5)
	pdf.Cell(0, 8, "This report is confidential and intended for the designated recipient only.")

	// Get PDF bytes
	var buf []byte
	buf = pdf.Output(nil)
	
	return buf, nil
}

// GenerateWarrantyCertificate generates a warranty certificate PDF
func GenerateWarrantyCertificate(validation *models.Validation, warrantyID string) ([]byte, error) {
	pdf := gofpdf.New("L", "mm", "A4", "") // Landscape
	pdf.AddPage()

	// Certificate Border
	pdf.SetDrawColor(31, 78, 121)
	pdf.SetLineWidth(2)
	pdf.Rect(10, 10, 277, 190, "D")

	pdf.SetLineWidth(0.5)
	pdf.Rect(15, 15, 267, 180, "D")

	// Header
	pdf.SetFont("Arial", "B", 32)
	pdf.SetTextColor(31, 78, 121)
	pdf.SetY(40)
	pdf.CellFormat(0, 15, "WARRANTY CERTIFICATE", "", 0, "C", false, 0, "")
	pdf.Ln(20)

	// Synthos AI
	pdf.SetFont("Arial", "I", 14)
	pdf.SetTextColor(128, 128, 128)
	pdf.CellFormat(0, 10, "Synthos AI", "", 0, "C", false, 0, "")
	pdf.Ln(20)

	// Certificate Body
	pdf.SetFont("Arial", "", 14)
	pdf.SetTextColor(0, 0, 0)
	pdf.CellFormat(0, 10, "This certifies that the dataset validation", "", 0, "C", false, 0, "")
	pdf.Ln(10)

	pdf.SetFont("Arial", "B", 16)
	pdf.CellFormat(0, 10, validation.ID, "", 0, "C", false, 0, "")
	pdf.Ln(12)

	pdf.SetFont("Arial", "", 14)
	pdf.CellFormat(0, 10, "has been issued a warranty under certificate", "", 0, "C", false, 0, "")
	pdf.Ln(10)

	pdf.SetFont("Arial", "B", 16)
	pdf.SetTextColor(31, 78, 121)
	pdf.CellFormat(0, 10, warrantyID, "", 0, "C", false, 0, "")
	pdf.Ln(15)

	// Warranty Details
	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(0, 0, 0)
	if validation.WarrantyEligible != nil && *validation.WarrantyEligible {
		pdf.CellFormat(0, 8, "This validation meets all quality standards for warranty coverage.", "", 0, "C", false, 0, "")
		pdf.Ln(8)
		pdf.CellFormat(0, 8, "Valid for 12 months from the date of issue.", "", 0, "C", false, 0, "")
	}
	pdf.Ln(15)

	// Date
	pdf.SetFont("Arial", "I", 12)
	pdf.SetTextColor(128, 128, 128)
	if validation.CompletedAt != nil {
		pdf.CellFormat(0, 8, "Issued on: "+validation.CompletedAt.Format("January 2, 2006"), "", 0, "C", false, 0, "")
	}

	// Seal/Watermark
	pdf.SetY(160)
	pdf.SetFont("Arial", "B", 10)
	pdf.SetTextColor(200, 200, 200)
	pdf.CellFormat(0, 8, "OFFICIAL SYNTHOS AI WARRANTY CERTIFICATE", "", 0, "C", false, 0, "")

	// Get PDF bytes
	var buf []byte
	buf = pdf.Output(nil)
	
	return buf, nil
}
