steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/synthos/api-gateway:latest', '-f', 'go_backend/Dockerfile', '.']
images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/synthos/api-gateway:latest'
options:
  machineType: 'E2_HIGHCPU_8'
timeout: '600s'
