package logger
package logger













































































}	return nil	}		return log.Sync()	if log != nil {func Sync() error {// Sync flushes any buffered log entries}	return Get().With(fields...)func With(fields ...zap.Field) *zap.Logger {// With creates a child logger with the given fields}	Get().Fatal(msg, fields...)func Fatal(msg string, fields ...zap.Field) {// Fatal logs a fatal message and exits}	Get().Debug(msg, fields...)func Debug(msg string, fields ...zap.Field) {// Debug logs a debug message}	Get().Warn(msg, fields...)func Warn(msg string, fields ...zap.Field) {// Warn logs a warning message}	Get().Error(msg, fields...)func Error(msg string, fields ...zap.Field) {// Error logs an error message}	Get().Info(msg, fields...)func Info(msg string, fields ...zap.Field) {// Info logs an info message}	return log	}		log, _ = zap.NewDevelopment()		// Fallback to development logger	if log == nil {func Get() *zap.Logger {// Get returns the global logger}	return nil		}		return err	if err != nil {	log, err = config.Build(zap.AddCallerSkip(1))	var err error		}		config.EncoderConfig.EncodeLevel = zapcore.CapitalColorLevelEncoder		config = zap.NewDevelopmentConfig()	} else {		config.EncoderConfig.EncodeTime = zapcore.ISO8601TimeEncoder		config.EncoderConfig.TimeKey = "timestamp"		config = zap.NewProductionConfig()	if environment == "production" {		var config zap.Configfunc Init(environment string) error {// Init initializes the global loggervar log *zap.Logger)	"go.uber.org/zap/zapcore"	"go.uber.org/zap"	"go.uber.org/zap"import (