package errors
package errors

import (
	"fmt"
	"net/http"
























































































































}	})		Error: *appErr,	return c.Status(appErr.StatusCode).JSON(ErrorResponse{		appErr.TraceID = traceID		}		appErr = InternalServer("An unexpected error occurred")		// Convert generic errors to AppError	if !ok {	appErr, ok := err.(*AppError)		traceID := c.Locals("trace_id").(string)func HandleError(c *fiber.Ctx, err error) error {// HandleError handles errors in Fiber context}	Error AppError `json:"error"`type ErrorResponse struct {// ErrorResponse formats the error response}	return NewAppError(ErrTimeout, message, http.StatusRequestTimeout)func Timeout(message string) *AppError {}	return NewAppError(ErrServiceUnavailable, message, http.StatusServiceUnavailable)func ServiceUnavailable(message string) *AppError {}	return NewAppError(ErrRateLimit, message, http.StatusTooManyRequests)func RateLimitExceeded(message string) *AppError {}	return NewAppError(ErrValidation, message, http.StatusBadRequest)func ValidationError(message string) *AppError {}	return NewAppError(ErrInternalServer, message, http.StatusInternalServerError)func InternalServer(message string) *AppError {}	return NewAppError(ErrConflict, message, http.StatusConflict)func Conflict(message string) *AppError {}	return NewAppError(ErrNotFound, message, http.StatusNotFound)func NotFound(message string) *AppError {}	return NewAppError(ErrForbidden, message, http.StatusForbidden)func Forbidden(message string) *AppError {}	return NewAppError(ErrUnauthorized, message, http.StatusUnauthorized)func Unauthorized(message string) *AppError {}	return NewAppError(ErrBadRequest, message, http.StatusBadRequest)func BadRequest(message string) *AppError {// Standard error constructors}	return e	e.TraceID = traceIDfunc (e *AppError) WithTraceID(traceID string) *AppError {// WithTraceID adds trace ID to the error}	return e	e.Details[key] = valuefunc (e *AppError) WithDetails(key, value string) *AppError {// WithDetails adds details to the error}	}		Details:    make(map[string]string),		StatusCode: statusCode,		Message:    message,		Code:       code,	return &AppError{func NewAppError(code ErrorCode, message string, statusCode int) *AppError {// NewAppError creates a new application error}	return fmt.Sprintf("[%s] %s", e.Code, e.Message)func (e *AppError) Error() string {// Error implements the error interface}	TraceID    string            `json:"trace_id,omitempty"`	StatusCode int               `json:"-"`	Details    map[string]string `json:"details,omitempty"`	Message    string            `json:"message"`	Code       ErrorCode         `json:"code"`type AppError struct {// AppError represents a standardized application error)	ErrInvalidCredentials ErrorCode = "INVALID_CREDENTIALS"	ErrDatabaseError      ErrorCode = "DATABASE_ERROR"	ErrTimeout            ErrorCode = "REQUEST_TIMEOUT"	ErrServiceUnavailable ErrorCode = "SERVICE_UNAVAILABLE"	ErrRateLimit          ErrorCode = "RATE_LIMIT_EXCEEDED"	ErrValidation         ErrorCode = "VALIDATION_ERROR"	ErrConflict           ErrorCode = "CONFLICT"	ErrNotFound           ErrorCode = "NOT_FOUND"	ErrForbidden          ErrorCode = "FORBIDDEN"	ErrUnauthorized       ErrorCode = "UNAUTHORIZED"	ErrBadRequest         ErrorCode = "BAD_REQUEST"	ErrInternalServer     ErrorCode = "INTERNAL_SERVER_ERROR"const (type ErrorCode string// ErrorCode represents standardized error codes)	"github.com/gofiber/fiber/v2"