# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import job_orchestrator_pb2 as job__orchestrator__pb2
except ImportError:
    import job_orchestrator_pb2 as job__orchestrator__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in job_orchestrator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobOrchestratorStub(object):
    """============================================================================
    Job Orchestrator Service
    ML Backend communicates with the Go Job Orchestrator via gRPC
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcknowledgeJob = channel.unary_unary(
                '/job_orchestrator.JobOrchestrator/AcknowledgeJob',
                request_serializer=job__orchestrator__pb2.JobAck.SerializeToString,
                response_deserializer=job__orchestrator__pb2.JobAckResponse.FromString,
                _registered_method=True)
        self.UpdateJobProgress = channel.unary_unary(
                '/job_orchestrator.JobOrchestrator/UpdateJobProgress',
                request_serializer=job__orchestrator__pb2.JobProgress.SerializeToString,
                response_deserializer=job__orchestrator__pb2.JobProgressResponse.FromString,
                _registered_method=True)
        self.CompleteJob = channel.unary_unary(
                '/job_orchestrator.JobOrchestrator/CompleteJob',
                request_serializer=job__orchestrator__pb2.JobCompletion.SerializeToString,
                response_deserializer=job__orchestrator__pb2.JobCompletionResponse.FromString,
                _registered_method=True)
        self.FailJob = channel.unary_unary(
                '/job_orchestrator.JobOrchestrator/FailJob',
                request_serializer=job__orchestrator__pb2.JobFailure.SerializeToString,
                response_deserializer=job__orchestrator__pb2.JobFailureResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/job_orchestrator.JobOrchestrator/Heartbeat',
                request_serializer=job__orchestrator__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=job__orchestrator__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class JobOrchestratorServicer(object):
    """============================================================================
    Job Orchestrator Service
    ML Backend communicates with the Go Job Orchestrator via gRPC
    ============================================================================

    """

    def AcknowledgeJob(self, request, context):
        """Job lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateJobProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat to indicate worker is alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcknowledgeJob': grpc.unary_unary_rpc_method_handler(
                    servicer.AcknowledgeJob,
                    request_deserializer=job__orchestrator__pb2.JobAck.FromString,
                    response_serializer=job__orchestrator__pb2.JobAckResponse.SerializeToString,
            ),
            'UpdateJobProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateJobProgress,
                    request_deserializer=job__orchestrator__pb2.JobProgress.FromString,
                    response_serializer=job__orchestrator__pb2.JobProgressResponse.SerializeToString,
            ),
            'CompleteJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteJob,
                    request_deserializer=job__orchestrator__pb2.JobCompletion.FromString,
                    response_serializer=job__orchestrator__pb2.JobCompletionResponse.SerializeToString,
            ),
            'FailJob': grpc.unary_unary_rpc_method_handler(
                    servicer.FailJob,
                    request_deserializer=job__orchestrator__pb2.JobFailure.FromString,
                    response_serializer=job__orchestrator__pb2.JobFailureResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=job__orchestrator__pb2.HeartbeatRequest.FromString,
                    response_serializer=job__orchestrator__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'job_orchestrator.JobOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('job_orchestrator.JobOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobOrchestrator(object):
    """============================================================================
    Job Orchestrator Service
    ML Backend communicates with the Go Job Orchestrator via gRPC
    ============================================================================

    """

    @staticmethod
    def AcknowledgeJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/job_orchestrator.JobOrchestrator/AcknowledgeJob',
            job__orchestrator__pb2.JobAck.SerializeToString,
            job__orchestrator__pb2.JobAckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateJobProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/job_orchestrator.JobOrchestrator/UpdateJobProgress',
            job__orchestrator__pb2.JobProgress.SerializeToString,
            job__orchestrator__pb2.JobProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/job_orchestrator.JobOrchestrator/CompleteJob',
            job__orchestrator__pb2.JobCompletion.SerializeToString,
            job__orchestrator__pb2.JobCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/job_orchestrator.JobOrchestrator/FailJob',
            job__orchestrator__pb2.JobFailure.SerializeToString,
            job__orchestrator__pb2.JobFailureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/job_orchestrator.JobOrchestrator/Heartbeat',
            job__orchestrator__pb2.HeartbeatRequest.SerializeToString,
            job__orchestrator__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
