# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import validation_pb2 as validation__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in validation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ValidationServiceStub(object):
    """Validation Service - Handles cascade training and diversity analysis
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrainCascade = channel.unary_unary(
                '/validation.ValidationService/TrainCascade',
                request_serializer=validation__pb2.TrainCascadeRequest.SerializeToString,
                response_deserializer=validation__pb2.TrainCascadeResponse.FromString,
                _registered_method=True)
        self.AnalyzeDiversity = channel.unary_unary(
                '/validation.ValidationService/AnalyzeDiversity',
                request_serializer=validation__pb2.AnalyzeDiversityRequest.SerializeToString,
                response_deserializer=validation__pb2.AnalyzeDiversityResponse.FromString,
                _registered_method=True)
        self.GetTrainingProgress = channel.unary_unary(
                '/validation.ValidationService/GetTrainingProgress',
                request_serializer=validation__pb2.ProgressRequest.SerializeToString,
                response_deserializer=validation__pb2.ProgressResponse.FromString,
                _registered_method=True)
        self.CancelTraining = channel.unary_unary(
                '/validation.ValidationService/CancelTraining',
                request_serializer=validation__pb2.CancelRequest.SerializeToString,
                response_deserializer=validation__pb2.CancelResponse.FromString,
                _registered_method=True)


class ValidationServiceServicer(object):
    """Validation Service - Handles cascade training and diversity analysis
    """

    def TrainCascade(self, request, context):
        """Train cascade of models for validation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeDiversity(self, request, context):
        """Analyze dataset diversity
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingProgress(self, request, context):
        """Get training progress
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTraining(self, request, context):
        """Cancel training job
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValidationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrainCascade': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainCascade,
                    request_deserializer=validation__pb2.TrainCascadeRequest.FromString,
                    response_serializer=validation__pb2.TrainCascadeResponse.SerializeToString,
            ),
            'AnalyzeDiversity': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeDiversity,
                    request_deserializer=validation__pb2.AnalyzeDiversityRequest.FromString,
                    response_serializer=validation__pb2.AnalyzeDiversityResponse.SerializeToString,
            ),
            'GetTrainingProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingProgress,
                    request_deserializer=validation__pb2.ProgressRequest.FromString,
                    response_serializer=validation__pb2.ProgressResponse.SerializeToString,
            ),
            'CancelTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTraining,
                    request_deserializer=validation__pb2.CancelRequest.FromString,
                    response_serializer=validation__pb2.CancelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'validation.ValidationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('validation.ValidationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ValidationService(object):
    """Validation Service - Handles cascade training and diversity analysis
    """

    @staticmethod
    def TrainCascade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/validation.ValidationService/TrainCascade',
            validation__pb2.TrainCascadeRequest.SerializeToString,
            validation__pb2.TrainCascadeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeDiversity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/validation.ValidationService/AnalyzeDiversity',
            validation__pb2.AnalyzeDiversityRequest.SerializeToString,
            validation__pb2.AnalyzeDiversityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/validation.ValidationService/GetTrainingProgress',
            validation__pb2.ProgressRequest.SerializeToString,
            validation__pb2.ProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/validation.ValidationService/CancelTraining',
            validation__pb2.CancelRequest.SerializeToString,
            validation__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
