# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import validation_pb2 as validation__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in validation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ValidationEngineStub(object):
    """============================================================================
    Validation Engine Service
    Handles Phase 2-6 of the validation pipeline
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeDiversity = channel.unary_unary(
                '/validation.ValidationEngine/AnalyzeDiversity',
                request_serializer=validation__pb2.DiversityRequest.SerializeToString,
                response_deserializer=validation__pb2.DiversityResponse.FromString,
                _registered_method=True)
        self.PreScreenRisk = channel.unary_unary(
                '/validation.ValidationEngine/PreScreenRisk',
                request_serializer=validation__pb2.PreScreenRequest.SerializeToString,
                response_deserializer=validation__pb2.PreScreenResponse.FromString,
                _registered_method=True)
        self.TrainCascade = channel.unary_stream(
                '/validation.ValidationEngine/TrainCascade',
                request_serializer=validation__pb2.CascadeRequest.SerializeToString,
                response_deserializer=validation__pb2.CascadeProgress.FromString,
                _registered_method=True)
        self.GetPredictions = channel.unary_unary(
                '/validation.ValidationEngine/GetPredictions',
                request_serializer=validation__pb2.PredictionRequest.SerializeToString,
                response_deserializer=validation__pb2.PredictionResponse.FromString,
                _registered_method=True)


class ValidationEngineServicer(object):
    """============================================================================
    Validation Engine Service
    Handles Phase 2-6 of the validation pipeline
    ============================================================================

    """

    def AnalyzeDiversity(self, request, context):
        """Phase 2: Analyze diversity and create stratified sample
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreScreenRisk(self, request, context):
        """Phase 3: Pre-screen against collapse signature library
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainCascade(self, request, context):
        """Phase 4: Multi-scale cascade training (STREAMING every 10s)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPredictions(self, request, context):
        """Phase 5: Get final predictions with confidence intervals
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValidationEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeDiversity': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeDiversity,
                    request_deserializer=validation__pb2.DiversityRequest.FromString,
                    response_serializer=validation__pb2.DiversityResponse.SerializeToString,
            ),
            'PreScreenRisk': grpc.unary_unary_rpc_method_handler(
                    servicer.PreScreenRisk,
                    request_deserializer=validation__pb2.PreScreenRequest.FromString,
                    response_serializer=validation__pb2.PreScreenResponse.SerializeToString,
            ),
            'TrainCascade': grpc.unary_stream_rpc_method_handler(
                    servicer.TrainCascade,
                    request_deserializer=validation__pb2.CascadeRequest.FromString,
                    response_serializer=validation__pb2.CascadeProgress.SerializeToString,
            ),
            'GetPredictions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPredictions,
                    request_deserializer=validation__pb2.PredictionRequest.FromString,
                    response_serializer=validation__pb2.PredictionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'validation.ValidationEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('validation.ValidationEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ValidationEngine(object):
    """============================================================================
    Validation Engine Service
    Handles Phase 2-6 of the validation pipeline
    ============================================================================

    """

    @staticmethod
    def AnalyzeDiversity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/validation.ValidationEngine/AnalyzeDiversity',
            validation__pb2.DiversityRequest.SerializeToString,
            validation__pb2.DiversityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreScreenRisk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/validation.ValidationEngine/PreScreenRisk',
            validation__pb2.PreScreenRequest.SerializeToString,
            validation__pb2.PreScreenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrainCascade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/validation.ValidationEngine/TrainCascade',
            validation__pb2.CascadeRequest.SerializeToString,
            validation__pb2.CascadeProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPredictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/validation.ValidationEngine/GetPredictions',
            validation__pb2.PredictionRequest.SerializeToString,
            validation__pb2.PredictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CollapseEngineStub(object):
    """============================================================================
    Collapse Engine Service  
    Handles collapse detection and localization
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectCollapse = channel.unary_unary(
                '/validation.CollapseEngine/DetectCollapse',
                request_serializer=validation__pb2.CollapseRequest.SerializeToString,
                response_deserializer=validation__pb2.CollapseResponse.FromString,
                _registered_method=True)
        self.LocalizeProblems = channel.unary_unary(
                '/validation.CollapseEngine/LocalizeProblems',
                request_serializer=validation__pb2.LocalizationRequest.SerializeToString,
                response_deserializer=validation__pb2.LocalizationResponse.FromString,
                _registered_method=True)
        self.GenerateRecommendations = channel.unary_unary(
                '/validation.CollapseEngine/GenerateRecommendations',
                request_serializer=validation__pb2.RecommendationRequest.SerializeToString,
                response_deserializer=validation__pb2.RecommendationResponse.FromString,
                _registered_method=True)


class CollapseEngineServicer(object):
    """============================================================================
    Collapse Engine Service  
    Handles collapse detection and localization
    ============================================================================

    """

    def DetectCollapse(self, request, context):
        """Phase 5: Detect collapse in cascade results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LocalizeProblems(self, request, context):
        """Phase 6: Pinpoint problematic data regions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateRecommendations(self, request, context):
        """Phase 6: Generate actionable recommendations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollapseEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectCollapse': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectCollapse,
                    request_deserializer=validation__pb2.CollapseRequest.FromString,
                    response_serializer=validation__pb2.CollapseResponse.SerializeToString,
            ),
            'LocalizeProblems': grpc.unary_unary_rpc_method_handler(
                    servicer.LocalizeProblems,
                    request_deserializer=validation__pb2.LocalizationRequest.FromString,
                    response_serializer=validation__pb2.LocalizationResponse.SerializeToString,
            ),
            'GenerateRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateRecommendations,
                    request_deserializer=validation__pb2.RecommendationRequest.FromString,
                    response_serializer=validation__pb2.RecommendationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'validation.CollapseEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('validation.CollapseEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CollapseEngine(object):
    """============================================================================
    Collapse Engine Service  
    Handles collapse detection and localization
    ============================================================================

    """

    @staticmethod
    def DetectCollapse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/validation.CollapseEngine/DetectCollapse',
            validation__pb2.CollapseRequest.SerializeToString,
            validation__pb2.CollapseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LocalizeProblems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/validation.CollapseEngine/LocalizeProblems',
            validation__pb2.LocalizationRequest.SerializeToString,
            validation__pb2.LocalizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/validation.CollapseEngine/GenerateRecommendations',
            validation__pb2.RecommendationRequest.SerializeToString,
            validation__pb2.RecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
