package tests














































































































































































































































}	assert.Equal(t, "queued", valResp.Status)	assert.NotEmpty(t, valResp.ValidationID)	json.NewDecoder(resp.Body).Decode(&valResp)	var valResp models.CreateValidationResponse	assert.Equal(t, http.StatusCreated, resp.StatusCode)	require.NoError(t, err)	resp, err = app.Test(req, -1)	req.Header.Set("Content-Type", "application/json")	req = httptest.NewRequest("POST", "/api/v1/validations", bytes.NewReader(body))	body, _ = json.Marshal(valReq)	}		},			Priority: "standard",		Options: models.ValidationOptions{		DatasetID: datasetID,	valReq := models.CreateValidationRequest{	// Step 3: Create validation	assert.Equal(t, http.StatusOK, resp.StatusCode)	require.NoError(t, err)	resp, err = app.Test(req, -1)	req.Header.Set("Content-Type", "application/json")	req = httptest.NewRequest("POST", "/api/v1/datasets/"+datasetID+"/complete", bytes.NewReader(body))	body, _ = json.Marshal(completeReq)	completeReq := models.CompleteUploadRequest{}	// Step 2: Complete upload	datasetID := uploadResp.DatasetID	json.NewDecoder(resp.Body).Decode(&uploadResp)	var uploadResp models.InitiateUploadResponse	assert.Equal(t, http.StatusOK, resp.StatusCode)	require.NoError(t, err)	resp, err := app.Test(req, -1)	req.Header.Set("Content-Type", "application/json")	req := httptest.NewRequest("POST", "/api/v1/datasets/upload", bytes.NewReader(body))	body, _ := json.Marshal(uploadReq)	}		Description: "Workflow test dataset",		FileType:    "text/csv",		FileSize:    1048576,		Filename:    "workflow_test.csv",	uploadReq := models.InitiateUploadRequest{	// Step 1: Upload dataset	app.Get("/api/v1/validations/:id", handlers.GetValidationFiber)	app.Post("/api/v1/validations", handlers.CreateValidationFiber)	app.Post("/api/v1/datasets/:id/complete", handlers.CompleteUploadFiber)	app.Post("/api/v1/datasets/upload", handlers.InitiateUploadFiber)	// Register routes	})		return c.Next()		c.Locals("user_id", "test_user_workflow")	app.Use(func(c *fiber.Ctx) error {	// Mock auth middleware	app := fiber.New()func TestValidationWorkflow(t *testing.T) {// Integration test: Full validation workflow}	})		assert.Equal(t, http.StatusOK, resp.StatusCode)		require.NoError(t, err)		resp, err := app.Test(req, -1)		req := httptest.NewRequest("GET", "/api/v1/validations?page=1&page_size=20", nil)	t.Run("ListValidations", func(t *testing.T) {	})		assert.Equal(t, http.StatusCreated, resp.StatusCode)		require.NoError(t, err)		resp, err := app.Test(req, -1)		req.Header.Set("Content-Type", "application/json")		req := httptest.NewRequest("POST", "/api/v1/validations", bytes.NewReader(body))		body, _ := json.Marshal(reqBody)		}			},				Priority: "standard",			Options: models.ValidationOptions{			DatasetID: "ds_test123",		reqBody := models.CreateValidationRequest{	t.Run("CreateValidation", func(t *testing.T) {	app.Get("/api/v1/validations/:id", handlers.GetValidationFiber)	app.Get("/api/v1/validations", handlers.ListValidationsFiber)	app.Post("/api/v1/validations", handlers.CreateValidationFiber)	})		return c.Next()		c.Locals("user_id", "test_user_001")	app.Use(func(c *fiber.Ctx) error {	// Mock authentication middleware	app := fiber.New()func TestValidationHandlers(t *testing.T) {// TestValidationHandlers tests validation endpoints}	})		assert.Equal(t, http.StatusOK, resp.StatusCode)		require.NoError(t, err)		resp, err := app.Test(req, -1)		req := httptest.NewRequest("GET", "/api/v1/datasets?page=1&page_size=20", nil)	t.Run("ListDatasets", func(t *testing.T) {	})		assert.Equal(t, http.StatusOK, resp.StatusCode)		require.NoError(t, err)		resp, err := app.Test(req, -1)		req.Header.Set("Content-Type", "application/json")		req := httptest.NewRequest("POST", "/api/v1/datasets/upload", bytes.NewReader(body))		body, _ := json.Marshal(reqBody)		}			Description: "Test dataset",			FileType:    "text/csv",			FileSize:    1048576,			Filename:    "test_dataset.csv",		reqBody := models.InitiateUploadRequest{	t.Run("InitiateUpload", func(t *testing.T) {	app.Get("/api/v1/datasets/:id", handlers.GetDatasetFiber)	app.Get("/api/v1/datasets", handlers.ListDatasetsFiber)	app.Post("/api/v1/datasets/upload", handlers.InitiateUploadFiber)	})		return c.Next()		c.Locals("user_id", "test_user_001")	app.Use(func(c *fiber.Ctx) error {	// Mock authentication middleware	app := fiber.New()func TestDatasetHandlers(t *testing.T) {// TestDatasetHandlers tests dataset endpoints}	})		assert.Equal(t, http.StatusUnauthorized, resp.StatusCode)		require.NoError(t, err)		resp, err := app.Test(req, -1)		req.Header.Set("Content-Type", "application/json")		req := httptest.NewRequest("POST", "/api/v1/auth/login", bytes.NewReader(body))		body, _ := json.Marshal(loginBody)		}			Password: "WrongPassword",			Email:    "nonexistent@example.com",		loginBody := models.LoginRequest{	t.Run("LoginInvalidCredentials", func(t *testing.T) {	})		assert.NotEmpty(t, response.RefreshToken)		assert.NotEmpty(t, response.AccessToken)		json.NewDecoder(resp.Body).Decode(&response)		var response models.LoginResponse		assert.Equal(t, http.StatusOK, resp.StatusCode)		require.NoError(t, err)		resp, err := app.Test(req, -1)		req.Header.Set("Content-Type", "application/json")		req = httptest.NewRequest("POST", "/api/v1/auth/login", bytes.NewReader(body))		body, _ = json.Marshal(loginBody)		}			Password: "SecurePass123!",			Email:    "login@example.com",		loginBody := models.LoginRequest{		// Then login		_, _ = app.Test(req, -1)		req.Header.Set("Content-Type", "application/json")		req := httptest.NewRequest("POST", "/api/v1/auth/register", bytes.NewReader(body))		body, _ := json.Marshal(regBody)		}			CompanyName: "Login Company",			FullName:    "Login User",			Password:    "SecurePass123!",			Email:       "login@example.com",		regBody := models.RegisterRequest{		// First register	t.Run("LoginSuccess", func(t *testing.T) {	})		assert.Equal(t, http.StatusCreated, resp.StatusCode)		require.NoError(t, err)		resp, err := app.Test(req, -1)		req.Header.Set("Content-Type", "application/json")		req := httptest.NewRequest("POST", "/api/v1/auth/register", bytes.NewReader(body))		body, _ := json.Marshal(reqBody)		}			CompanyName: "Test Company",			FullName:    "Test User",			Password:    "SecurePass123!",			Email:       "test@example.com",		reqBody := models.RegisterRequest{	t.Run("RegisterSuccess", func(t *testing.T) {	app.Post("/api/v1/auth/refresh", handlers.RefreshTokenFiber)	app.Post("/api/v1/auth/login", handlers.LoginFiber)	app.Post("/api/v1/auth/register", handlers.RegisterFiber)	app := fiber.New()func TestAuthHandlers(t *testing.T) {// TestAuthHandlers tests authentication endpoints)	"github.com/tafolabi009/backend/go_backend/internal/models"	"github.com/tafolabi009/backend/go_backend/internal/handlers"	"github.com/stretchr/testify/require"	"github.com/stretchr/testify/assert"	"github.com/gofiber/fiber/v2"	"testing"	"net/http/httptest"	"net/http"	"encoding/json"	"bytes"import (package tests