# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import collapse_pb2 as collapse__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in collapse_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CollapseServiceStub(object):
    """Collapse Service - Handles collapse detection, localization, and recommendations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectCollapse = channel.unary_unary(
                '/collapse.CollapseService/DetectCollapse',
                request_serializer=collapse__pb2.DetectCollapseRequest.SerializeToString,
                response_deserializer=collapse__pb2.DetectCollapseResponse.FromString,
                _registered_method=True)
        self.LocalizeCollapse = channel.unary_unary(
                '/collapse.CollapseService/LocalizeCollapse',
                request_serializer=collapse__pb2.LocalizeCollapseRequest.SerializeToString,
                response_deserializer=collapse__pb2.LocalizeCollapseResponse.FromString,
                _registered_method=True)
        self.GenerateRecommendations = channel.unary_unary(
                '/collapse.CollapseService/GenerateRecommendations',
                request_serializer=collapse__pb2.RecommendationsRequest.SerializeToString,
                response_deserializer=collapse__pb2.RecommendationsResponse.FromString,
                _registered_method=True)
        self.GenerateAdvancedRecommendations = channel.unary_unary(
                '/collapse.CollapseService/GenerateAdvancedRecommendations',
                request_serializer=collapse__pb2.AdvancedRecommendationsRequest.SerializeToString,
                response_deserializer=collapse__pb2.AdvancedRecommendationsResponse.FromString,
                _registered_method=True)
        self.CheckSignatureLibrary = channel.unary_unary(
                '/collapse.CollapseService/CheckSignatureLibrary',
                request_serializer=collapse__pb2.SignatureCheckRequest.SerializeToString,
                response_deserializer=collapse__pb2.SignatureCheckResponse.FromString,
                _registered_method=True)


class CollapseServiceServicer(object):
    """Collapse Service - Handles collapse detection, localization, and recommendations
    """

    def DetectCollapse(self, request, context):
        """Detect mode collapse in dataset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LocalizeCollapse(self, request, context):
        """Localize collapse points in dataset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateRecommendations(self, request, context):
        """Generate fix recommendations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateAdvancedRecommendations(self, request, context):
        """Generate advanced recommendations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSignatureLibrary(self, request, context):
        """Check signature library for known patterns
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollapseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectCollapse': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectCollapse,
                    request_deserializer=collapse__pb2.DetectCollapseRequest.FromString,
                    response_serializer=collapse__pb2.DetectCollapseResponse.SerializeToString,
            ),
            'LocalizeCollapse': grpc.unary_unary_rpc_method_handler(
                    servicer.LocalizeCollapse,
                    request_deserializer=collapse__pb2.LocalizeCollapseRequest.FromString,
                    response_serializer=collapse__pb2.LocalizeCollapseResponse.SerializeToString,
            ),
            'GenerateRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateRecommendations,
                    request_deserializer=collapse__pb2.RecommendationsRequest.FromString,
                    response_serializer=collapse__pb2.RecommendationsResponse.SerializeToString,
            ),
            'GenerateAdvancedRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAdvancedRecommendations,
                    request_deserializer=collapse__pb2.AdvancedRecommendationsRequest.FromString,
                    response_serializer=collapse__pb2.AdvancedRecommendationsResponse.SerializeToString,
            ),
            'CheckSignatureLibrary': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSignatureLibrary,
                    request_deserializer=collapse__pb2.SignatureCheckRequest.FromString,
                    response_serializer=collapse__pb2.SignatureCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'collapse.CollapseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('collapse.CollapseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CollapseService(object):
    """Collapse Service - Handles collapse detection, localization, and recommendations
    """

    @staticmethod
    def DetectCollapse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collapse.CollapseService/DetectCollapse',
            collapse__pb2.DetectCollapseRequest.SerializeToString,
            collapse__pb2.DetectCollapseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LocalizeCollapse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collapse.CollapseService/LocalizeCollapse',
            collapse__pb2.LocalizeCollapseRequest.SerializeToString,
            collapse__pb2.LocalizeCollapseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collapse.CollapseService/GenerateRecommendations',
            collapse__pb2.RecommendationsRequest.SerializeToString,
            collapse__pb2.RecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateAdvancedRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collapse.CollapseService/GenerateAdvancedRecommendations',
            collapse__pb2.AdvancedRecommendationsRequest.SerializeToString,
            collapse__pb2.AdvancedRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckSignatureLibrary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/collapse.CollapseService/CheckSignatureLibrary',
            collapse__pb2.SignatureCheckRequest.SerializeToString,
            collapse__pb2.SignatureCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
